AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3BucketName:
    Type: String

Resources:

  BucketS3Principal:
    Type: "AWS::S3Bucket"
  Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true